br_wp:
 image: wordpress
 links:
  - br_wp_db:mysql
 ports:
  - 8080:80
 volumes:
  - .:/var/www/html # NOTE: may need to change this path to match your enviroment
br_wp_db:
 image: mariadb
 environment:
  MYSQL_ROOT_PASSWORD: examplepass
 volumes:
  - mysql-data:/var/lib/mysql # NOTE: may need to change this path to match your enviroment
br_phpmyadmin:
 image: corbinu/docker-phpmyadmin
 links:
  - br_wp_db:mysql
 ports:
  - 8181:80
 environment:
  MYSQL_USERNAME: root
  MYSQL_ROOT_PASSWORD: password
