br_wp:
 image: wordpress
 links:
  - br_wp_db:mysql
 ports:
  - 8080:80
 volumes:
  - ~/www/next-wp-rest/api:/var/www/html:delegated # NOTE: may need to change this path to match your enviroment
br_wp_db:
 image: mariadb
 environment:
  MYSQL_ROOT_PASSWORD: examplepass
 volumes:
  - ~/www/next-wp-rest/api/.database:/var/lib/mysql:delegated # NOTE: may need to change this path to match your enviroment
br_phpmyadmin:
 image: corbinu/docker-phpmyadmin
 links:
  - br_wp_db:mysql
 ports:
  - 8181:80
 environment:
  MYSQL_USERNAME: root
  MYSQL_ROOT_PASSWORD: password
